spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Login?characterEncoding=utf-8
    username: root
    password: cp731950LZY
server:
  port: 8088
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_null